"use client";

import { useState } from "react";
import { Mic } from "lucide-react";

interface InterviewAudioVaultProps {
  snippets: string[];
}

/**
 * Historical interview / primary-source audio clips (LessonInAppMedia.
 * audioSnippets) — generated by the model since Phase 1 (lib/learning/
 * agePromptEngine.ts already documents the field) but never rendered until
 * now; LessonViewport's MediaSection only ever read youtubeVideoId.
 *
 * Plain native <audio> elements — no reusable player component exists
 * anywhere in this app to build on (confirmed: even the Torah module's
 * AudioAttachmentWidget.tsx inlines one), and a lesson has at most a
 * handful of short clips, not enough to justify one.
 */
export function InterviewAudioVault({ snippets }: InterviewAudioVaultProps) {
  const [broken, setBroken] = useState<Set<number>>(new Set());
  const playable = snippets.map((src, i) => ({ src, i })).filter(({ i }) => !broken.has(i));

  if (playable.length === 0) return null;

  return (
    <div className="flex flex-col gap-3">
      {playable.map(({ src, i }) => (
        <div key={src} className="flex items-center gap-3 rounded-xl border border-hairline-card bg-surface p-3">
          <span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-accent-learning/15 text-accent-learning">
            <Mic size={14} aria-hidden />
          </span>
          <div className="min-w-0 flex-1">
            <p className="mb-1 text-xs font-medium text-muted">{`קטע ${i + 1}`}</p>
            <audio
              src={src}
              controls
              preload="none"
              className="w-full"
              aria-label={`קטע שמע ${i + 1}`}
              onError={() => setBroken((current) => new Set(current).add(i))}
            />
          </div>
        </div>
      ))}
    </div>
  );
}
