import { z } from "zod";
import { EXPENSE_KEYS, categoryLabelFor, type ExpenseCategoryKey } from "@/lib/finances/categories";

// The vocabulary of the floating quick-input (FAB). Deliberately free of
// "server-only" and of any DB import: the client needs the SOS matcher (so a
// distress message can be recognised before a single byte leaves the device),
// the result types, and the Hebrew summaries, and the server needs the same
// schemas. lib/ai/fabRouter.ts is the server half.

export const FAB_INTENTS = [
  "LOG_WATER",
  "LOG_EXPENSE",
  "ADD_TASK",
  "TORAH_INSIGHT",
  "CRM_INTERACTION",
  "PERSONAL_SPACE_SOS",
  "GENERAL_QUERY",
] as const;
export type FabIntent = (typeof FAB_INTENTS)[number];

// PERSONAL_SPACE_SOS is missing on purpose. A model that can emit it is a
// model that has been shown the message; the SOS path is decided locally by
// isSosMessage() below, before any model call, so the enum the model sees
// simply does not contain it.
export const MODEL_INTENTS = [
  "LOG_WATER",
  "LOG_EXPENSE",
  "ADD_TASK",
  "TORAH_INSIGHT",
  "CRM_INTERACTION",
  "GENERAL_QUERY",
] as const;

// --- Payloads -------------------------------------------------------------

export const waterPayloadSchema = z.object({
  /** A glass is 250 ml (lib/health/water.ts WATER_STEP_ML). */
  amountMl: z.number().int().min(50).max(2000),
});

// z.enum wants a non-empty tuple; EXPENSE_KEYS is the same closed list the
// FinanceAgent classifies into, typed as string[] for `.includes` callers.
const expenseCategoryEnum = z.enum(EXPENSE_KEYS as unknown as [ExpenseCategoryKey, ...ExpenseCategoryKey[]]);

export const expensePayloadSchema = z.object({
  /** Shekels. Positive — an expense is never entered as a negative number. */
  amount: z.number().positive().max(1_000_000),
  category: expenseCategoryEnum,
  title: z.string().trim().min(1).max(80),
});

const DUE_AT_PATTERN = /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2})?$/;

export const taskPayloadSchema = z.object({
  title: z.string().trim().min(1).max(200),
  /** "YYYY-MM-DDTHH:MM" in the user's local wall clock, or a bare date. */
  dueAt: z.string().regex(DUE_AT_PATTERN).optional(),
  priority: z.enum(["normal", "high"]),
});

export const torahInsightPayloadSchema = z.object({
  title: z.string().trim().min(1).max(80),
  content: z.string().trim().min(1).max(2000),
});

/** What the model says: a name as spoken. Resolving it to a real person is the server's job. */
export const crmSpokenPayloadSchema = z.object({
  contactName: z.string().trim().min(1).max(80),
  note: z.string().trim().max(500).optional(),
});

/** What the client receives: a person that really exists in this user's CRM. */
export const crmResolvedPayloadSchema = z.object({
  personId: z.string().min(1),
  personName: z.string().min(1),
  note: z.string().max(500).optional(),
});

// --- What the model returns ----------------------------------------------

// Flat, with one optional object per intent, rather than a discriminated
// union: that is the shape CommandIntentSchema already sends to Gemini and
// gets reliable structured output from, where anyOf/oneOf schemas are the
// part of structured output providers implement least evenly. The strict
// {intent, payload, confidence} union below is built from this afterward.
//
// No `reply` field: the confirmation text is generated by describeFabAction()
// from the validated payload, so it can never claim something the payload
// does not say — and it saves the model tokens on every keystroke-sized call.
export const FabModelOutputSchema = z.object({
  intent: z.enum(MODEL_INTENTS),
  confidence: z.number().min(0).max(1),
  logWater: waterPayloadSchema.optional(),
  logExpense: expensePayloadSchema.optional(),
  addTask: taskPayloadSchema.extend({ priority: z.enum(["normal", "high"]).optional() }).optional(),
  torahInsight: torahInsightPayloadSchema.optional(),
  crmInteraction: crmSpokenPayloadSchema.optional(),
});
export type FabModelOutput = z.infer<typeof FabModelOutputSchema>;

// --- The strict, spec-shaped result ---------------------------------------

const confidence = z.number().min(0).max(1);

export const AutoActionSchema = z.discriminatedUnion("intent", [
  z.object({ intent: z.literal("LOG_WATER"), payload: waterPayloadSchema, confidence }),
  z.object({ intent: z.literal("LOG_EXPENSE"), payload: expensePayloadSchema, confidence }),
  z.object({ intent: z.literal("ADD_TASK"), payload: taskPayloadSchema, confidence }),
]);
export type AutoAction = z.infer<typeof AutoActionSchema>;

export const ConfirmActionSchema = z.discriminatedUnion("intent", [
  z.object({ intent: z.literal("TORAH_INSIGHT"), payload: torahInsightPayloadSchema, confidence }),
  z.object({ intent: z.literal("CRM_INTERACTION"), payload: crmResolvedPayloadSchema, confidence }),
]);
export type ConfirmAction = z.infer<typeof ConfirmActionSchema>;

// --- Policy ---------------------------------------------------------------

/**
 * auto:    the write happens at once and the UI offers undo. Only for things
 *          that are cheap to be wrong about AND have a real undo.
 * confirm: a proposal the user approves or adjusts first (the app's standing
 *          "nothing auto-commits" rule, docs/ATLAS_SESSION_BRIEF.md §1.3).
 * sos:     open the Companion in SOS mode. Decided locally; see isSosMessage.
 * handoff: not a quick-log — the client forwards the text to the existing
 *          command pipeline / chat, which own calendar changes and answers.
 */
export type FabExecutionMode = "auto" | "confirm" | "sos" | "handoff";

export const EXECUTION_MODE: Record<FabIntent, FabExecutionMode> = {
  LOG_WATER: "auto",
  LOG_EXPENSE: "auto",
  ADD_TASK: "auto",
  // Would be "auto" too, but the store has no deleteMoment, so there is no
  // real undo to offer. Flip this when one exists.
  TORAH_INSIGHT: "confirm",
  CRM_INTERACTION: "confirm",
  PERSONAL_SPACE_SOS: "sos",
  GENERAL_QUERY: "handoff",
};

/**
 * Below this the model's own certainty is not enough to write anything. Money
 * is held higher than the rest: a misheard amount is the one auto-commit that
 * silently corrupts numbers the user will later trust.
 */
export const MIN_CONFIDENCE: Record<FabIntent, number> = {
  LOG_WATER: 0.7,
  LOG_EXPENSE: 0.8,
  ADD_TASK: 0.7,
  TORAH_INSIGHT: 0.7,
  CRM_INTERACTION: 0.7,
  PERSONAL_SPACE_SOS: 0,
  GENERAL_QUERY: 0,
};

// --- What the route sends back --------------------------------------------

export type FabHandoffReason = "general" | "low_confidence" | "invalid_payload" | "unavailable";

export type FabRouteResponse =
  | { mode: "auto"; action: AutoAction; summary: string }
  | { mode: "confirm"; action: ConfirmAction; summary: string; recommendationEventId: string }
  | { mode: "sos" }
  | { mode: "reply"; reply: string }
  | { mode: "handoff"; reason: FabHandoffReason };

export function describeFabAction(action: AutoAction | ConfirmAction): string {
  switch (action.intent) {
    case "LOG_WATER":
      return `נרשמו ${action.payload.amountMl} מ״ל מים`;
    case "LOG_EXPENSE":
      return `הוצאה: ${action.payload.title} · ${action.payload.amount} ₪ · ${categoryLabelFor(action.payload.category)}`;
    case "ADD_TASK": {
      const due = action.payload.dueAt ? ` · ${action.payload.dueAt.replace("T", " ")}` : "";
      return `משימה: ${action.payload.title}${due}${action.payload.priority === "high" ? " · דחוף" : ""}`;
    }
    case "TORAH_INSIGHT":
      return `חידוש תורה: ${action.payload.title}`;
    case "CRM_INTERACTION":
      return `לתעד שיחה עם ${action.payload.personName}`;
  }
}

// --- Local SOS detection ---------------------------------------------------

// The "קשה לי עכשיו" path (Pillar 3, Personal Space <-> Companion).
//
// Runs on the device, then again on the server before anything else — never
// through a model. The recovery space is locked so that nothing on screen or
// on disk reveals what it is for; a distress message that were sent to a
// third-party model, logged, or stored as a "recommendation event" would
// undo that. So a match here produces no model call, no quota charge, no
// database row and no log line.
//
// Deliberately narrow: the WHOLE message must be a distress phrase (plus
// filler like "עכשיו"). "קשה לי" alone or "קשה לי עכשיו" opens the Companion;
// "קשה לי להבין את הפרק" is a study question and must not. The cost of a
// false negative is that a message goes to the normal pipeline, where the
// model is told to treat distress as a plain conversation and nothing is
// persisted; the cost of a false positive is a calming screen nobody asked
// for. Narrow is the right side to err on for a shortcut people type fast.

const NIQQUD = /[֑-ׇ]/g;

const SOS_FILLERS = new Set([
  "אני",
  "ממש",
  "מאוד",
  "כל",
  "כך",
  "עכשיו",
  "כרגע",
  "ברגע",
  "היום",
  "מדי",
  "מידי",
  "באמת",
  "פשוט",
  "אחי",
  "בבקשה",
]);

const SOS_PHRASES = new Set([
  "קשה לי",
  "קשה",
  "לא מצליח",
  "לא מצליחה",
  "לא יכול יותר",
  "לא יכולה יותר",
  "לא עומד בזה",
  "לא עומדת בזה",
  "מרגיש רע",
  "מרגישה רע",
  "מרגיש נורא",
  "מרגישה נורא",
  "צריך עזרה",
  "צריכה עזרה",
  "עזרה",
  "במצוקה",
  "יש לי דחף",
  "נופל",
  "נופלת",
  "sos",
]);

function significantTokens(text: string): string[] {
  return text
    .normalize("NFKC")
    .replace(NIQQUD, "")
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .split(/\s+/)
    .filter((token) => token.length > 0 && !SOS_FILLERS.has(token));
}

export function isSosMessage(text: string): boolean {
  const tokens = significantTokens(text);
  if (tokens.length === 0 || tokens.length > 4) return false;
  return SOS_PHRASES.has(tokens.join(" "));
}
